"""WP-7 + WP-9 — de-automated migrate (C7/C11 gate, shadow-first, human-approval)
and ownership guard (banner detection + freshness).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

SCRIPT_DIR = Path(__file__).resolve().parent.parent / "scripts"
sys.path.insert(0, str(SCRIPT_DIR))

import migrate as migrate_mod  # noqa: E402
import ownership_guard  # noqa: E402


# ---------------------------------------------------------------------------
# ownership_guard (WP-9)
# ---------------------------------------------------------------------------


def test_is_generated_detects_banner(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("<!-- GENERATED by code-comprehension — do not hand-edit -->\n# x\n")
    assert ownership_guard.is_generated(p) is True


def test_is_generated_false_for_hand_doc(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("# Hand-written PROJECT.md\n")
    assert ownership_guard.is_generated(p) is False


def test_freshness_digest_extracted(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("<!-- FRESHNESS:v1 generated_from=0123456789abcdef -->\n")
    assert ownership_guard.freshness_digest(p) == "0123456789abcdef"


def test_freshness_ok_match_and_mismatch(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("<!-- FRESHNESS:v1 generated_from=0123456789abcdef -->\n")
    assert ownership_guard.freshness_ok(p, "0123456789abcdef") is True
    assert ownership_guard.freshness_ok(p, "ffffffffffffffff") is False


def test_lint_fails_on_stale_generated_doc(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("<!-- GENERATED by code-comprehension -->\n"
                 "<!-- FRESHNESS:v1 generated_from=aaaaaaaaaaaaaaaa -->\n")
    # expected digest differs → stale/edited → rc 2
    assert ownership_guard.lint_no_manual_edit(p, "bbbbbbbbbbbbbbbb") == 2
    # matching → rc 0
    assert ownership_guard.lint_no_manual_edit(p, "aaaaaaaaaaaaaaaa") == 0


def test_lint_ignores_non_generated_doc(tmp_path: Path) -> None:
    p = tmp_path / "PROJECT.md"
    p.write_text("# Hand-written\n")
    assert ownership_guard.lint_no_manual_edit(p, "anything") == 0


# ---------------------------------------------------------------------------
# migrate (WP-7) — C11 gate
# ---------------------------------------------------------------------------


_GOOD_PARTITION = {
    "components": [
        {"id": "a", "source_files": ["a/x.py"], "intent_mode": "llm"},
        {"id": "b", "source_files": ["b/y.py"], "intent_mode": "llm"},
    ]
}


def test_migrate_blocked_on_failed_component(tmp_path: Path) -> None:
    manifest = {"summary": {"failed": 1, "gap": 0}}
    reason = migrate_mod.migration_blocked_reason(manifest, _GOOD_PARTITION)
    assert reason is not None and "failed" in reason


def test_migrate_blocked_on_degraded_component(tmp_path: Path) -> None:
    part = {"components": [{"id": "a", "source_files": ["a/x.py"], "intent_mode": "degraded"}]}
    reason = migrate_mod.migration_blocked_reason({"summary": {}}, part)
    assert reason is not None and "degraded" in reason


def test_migrate_blocked_on_incomplete_coverage(tmp_path: Path) -> None:
    part = {"components": [{"id": "a", "source_files": [], "intent_mode": "llm"}]}
    reason = migrate_mod.migration_blocked_reason({"summary": {}}, part)
    assert reason is not None and "coverage" in reason


def test_migrate_clean_partition_not_blocked(tmp_path: Path) -> None:
    reason = migrate_mod.migration_blocked_reason({"summary": {"failed": 0, "gap": 0}}, _GOOD_PARTITION)
    assert reason is None


# ---------------------------------------------------------------------------
# migrate (WP-7) — shadow-first, archive, proposal, no overwrite without approval
# ---------------------------------------------------------------------------


def test_migrate_proposes_and_archives_without_overwrite(tmp_path: Path) -> None:
    project = tmp_path
    (project / "PROJECT.md").write_text(
        "# Project\n## Changelog\n- did x\n## Why\nbecause\n## Components\n| a | b |\n")
    result = migrate_mod.migrate(project, partition_doc=_GOOD_PARTITION,
                                 intent_manifest={"summary": {"failed": 0, "gap": 0}},
                                 apply=False)
    assert result["status"] == "proposed"
    # original archived byte-for-byte
    assert result["archived_count"] == 1
    manifest = json.loads(Path(result["manifest"]).read_text())
    assert manifest["applied"] is False
    # the real PROJECT.md is UNTOUCHED (shadow-first; no overwrite without approval)
    assert (project / "PROJECT.md").read_text().startswith("# Project")
    # proposal classifies sections into buckets
    headers = {s["header"]: s["suggest"] for s in manifest["proposed_split"]["sections"]}
    assert headers.get("Changelog") == "history.md"
    assert headers.get("Why") == "ARCHITECTURE.md"
    assert headers.get("Components") == "PROJECT.generated.md"


def test_migrate_blocked_returns_block_status(tmp_path: Path) -> None:
    project = tmp_path
    (project / "PROJECT.md").write_text("# x\n")
    bad_part = {"components": [{"id": "a", "source_files": ["a/x.py"], "intent_mode": "degraded"}]}
    result = migrate_mod.migrate(project, partition_doc=bad_part,
                                 intent_manifest={"summary": {}}, apply=False)
    assert result["status"] == "blocked"
    # nothing archived/migrated on a block
    assert not (project / ".comprehension" / "migration").exists()


def test_migrate_apply_requires_approvals(tmp_path: Path) -> None:
    project = tmp_path
    (project / "PROJECT.md").write_text("# x\n## Components\n")
    result = migrate_mod.migrate(project, partition_doc=_GOOD_PARTITION,
                                 intent_manifest={"summary": {"failed": 0, "gap": 0}},
                                 apply=True, approvals_path=None)
    assert result["status"] == "needs_approvals"
