"""test_header.py — Mandatory confidence header + pytest.mark metadata.

Every generated test file MUST start with this header. Skipping the header
is a HARD-RULE 2 / HARD-RULE 8 violation.
"""
from __future__ import annotations

from typing import Optional


PY_HEADER_TEMPLATE = '''"""
EVO-generated test — CONFIDENCE: {confidence_level}
This test was auto-generated by Evo from {source_basis}.
It captures observed legacy behaviour, NOT a correctness specification.
Requires user review before being relied on for refactor safety.

Source seed: {source_seed}
Wiring evidence: {wiring_evidence}
Mode: {mode}
Generated by: ever-test-gen@1.0.0
"""

import pytest

EVO_MARKERS = ["evo_generated", "evo_confidence:{confidence_level}", "evo_requires_review"]
'''


JS_HEADER_TEMPLATE = '''/**
 * EVO-generated test — CONFIDENCE: {confidence_level}
 * This test was auto-generated by Evo from {source_basis}.
 * It captures observed legacy behaviour, NOT a correctness specification.
 * Requires user review before being relied on for refactor safety.
 *
 * Source seed: {source_seed}
 * Wiring evidence: {wiring_evidence}
 * Mode: {mode}
 * Generated by: ever-test-gen@1.0.0
 */

const EVO_MARKERS = ["evo_generated", "evo_confidence:{confidence_level}", "evo_requires_review"];
'''


VALID_CONFIDENCE_LEVELS = ("characterization-aid", "regression-aid", "cve-proof-of-fix")
VALID_LANGUAGES = ("python", "javascript", "typescript")
VALID_MODES = ("version-upgrade", "cve-fix")


def build_header(
    *,
    language: str,
    confidence_level: str,
    mode: str,
    source_basis: str,
    source_seed: str,
    wiring_evidence: str,
) -> str:
    """Build the mandatory header for a generated test.

    Args:
        language: 'python' | 'javascript' | 'typescript'
        confidence_level: one of VALID_CONFIDENCE_LEVELS
        mode: 'version-upgrade' | 'cve-fix'
        source_basis: human-readable summary of the source signal
            (e.g. "intent-map.test_seeds[S-001] + api_delta.breaking_lines[2]")
        source_seed: stable id of the source signal (S-001, cve-xyz, etc.)
        wiring_evidence: snapshot_hash + symbol + site reference

    Raises:
        ValueError: on invalid enum value (defensive — caught at test time too)
    """
    if confidence_level not in VALID_CONFIDENCE_LEVELS:
        raise ValueError(f"invalid confidence_level: {confidence_level}")
    if mode not in VALID_MODES:
        raise ValueError(f"invalid mode: {mode}")
    if language not in VALID_LANGUAGES:
        raise ValueError(f"invalid language: {language}")

    fields = {
        "confidence_level": confidence_level,
        "source_basis": source_basis,
        "source_seed": source_seed,
        "wiring_evidence": wiring_evidence,
        "mode": mode,
    }
    if language == "python":
        return PY_HEADER_TEMPLATE.format(**fields)
    return JS_HEADER_TEMPLATE.format(**fields)


def header_present(text: str) -> bool:
    """Return True iff `text` starts with a recognisable evo header.

    Used by both this skill (defensive check) and by other consumers
    (e.g. trusted_runner verifying that a test was indeed evo-generated).
    """
    return (
        "EVO-generated test" in text
        and "CONFIDENCE:" in text
        and "Requires user review" in text
    )


def confidence_for_test_type(test_type: str) -> str:
    """Map test_type → confidence_level label."""
    return {
        "regression": "characterization-aid",
        "migration": "characterization-aid",
        "cve_proof": "cve-proof-of-fix",
    }.get(test_type, "characterization-aid")
