#!/usr/bin/env python3
"""Render the VS Code consultation handles from the declared roster (#274).

WHAT A HANDLE IS
----------------
Not a persona. An INSTRUMENT: a way to route one question to a DIFFERENT MODEL
inside the same Copilot session. On the Linux box, provider diversity comes from
CLI delegates (`codex exec`, `agy -p`). On the enterprise laptop those CLIs do not
exist -- and `cross-cli-deliberation` and `avengers` both assume a CLI transport,
so the entire anti-echo-chamber layer has NO transport there at all. VS Code's
model picker is the transport that IS available, and `model:` frontmatter is how
you reach it.

TWO CLASSES, KEPT APART ON PURPOSE
----------------------------------
  review  -> provider diversity. Carries the full two-gate protocol.
  cheap   -> tier discipline. Carries NO deliberation machinery.

Collapsing them is a live failure mode in this ecosystem, not a hypothetical: the
tempting fix for an agy no-show is `--model claude-sonnet-4-6`, which converts a
RECORDED provider gap into a HIDDEN one. A cheap-tier handle that carried a
"second opinion" protocol would do exactly that, one model tier down.

WHY IT REFUSES TO RENDER A PENDING ID
-------------------------------------
A wrong model id fails SILENTLY as a permissions error. Emitting a handle with a
placeholder would produce a file that looks installed, appears in the picker, and
quietly does not route -- the "looks wired, isn't" class this repo has shipped
four times. Refusing is loud; a placeholder is not.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - pyyaml is a declared core dep
    yaml = None

HERE = Path(__file__).resolve().parent
AGENTS_DIR = HERE.parent / "agents"
ROSTER = AGENTS_DIR / "roster.yaml"

PENDING = "PENDING-VERIFICATION"

GENERATED_MARKER = "<!-- generated by vs-code/scripts/render_handles.py — edit roster.yaml, not this file -->"

# Advisory-only is enforced by the TOOL LIST, not by asking nicely. Omitting
# editFiles and terminal is the VS Code equivalent of agy's --sandbox: a
# consultant that cannot write cannot "helpfully" refactor the thing it was asked
# to review. An un-sandboxed analyst has authored and git-committed code here
# before (S052, #157), which is why this is a mechanism and not a paragraph.
REVIEW_TOOLS = "['codebase', 'search', 'problems', 'changes']"
CHEAP_TOOLS = "['codebase', 'search', 'problems', 'changes', 'editFiles']"

REVIEW_BODY = """
# @{name} — consultation handle ({provider}, {tier})

**This is an instrument, not a persona.** You are being consulted for an
independent opinion inside someone else's coding session. You are running on
**{provider}**, deliberately different from the model that did the work, so that
the review is not the author marking their own homework.

{purpose}

## Provider honesty — read this before you are treated as independent

You are `provider: {provider}`.{diversity_note}

State your provider in your answer. If a reviewer records "a second model agreed"
without knowing whether that model shares the author's blind spots, the
cross-check is theatre and nobody can tell.

## Advisory only

Answer in chat. **Do not edit files.** Your tool list omits `editFiles` and
`terminal` by design — if the right answer needs a change, describe the change
precisely enough that someone else can make it, and let them.

## Gate 1 — Null-hypothesis ballot

**"No change needed" is the default incumbent that any proposed change must
defeat.** Pushback must be structural, not theatrical. File this BEFORE arguing
any position:

```
Verdict:    ACCEPT_AS_IS / REJECT_PREMISE / CHANGE_NEEDED
Confidence: 0-100
Burden met? — what evidence would justify changing this?
              has that evidence been provided in the artifact itself?
Expected loss:
  - if we adopt and shouldn't have:
  - if we don't adopt and should have:
Minimum acceptable action: no-op / clarifying question / test only / patch / redesign
```

Then declare on each of these failure modes, by name:

- **Ego** — defending a prior position as inviolate
- **Capture** — caving to the synthesis because it elevates your own prior contribution
- **Capture by capability** — caving to a higher-tier peer model
- **Sycophancy of dissent** — producing CHANGE_NEEDED to satisfy "produce something
  useful", with no admissible evidence

That last one is why you exist in this form. Being asked for a review is not
evidence that something is wrong.

## Gate 2 — Burden of falsification

If and only if you voted `CHANGE_NEEDED`, ship verifiable evidence in at least one
admissible class. **No admissible evidence → Null Verdict, and a failed
falsification is the strongest validation there is.**

1. **Reproduction** — (a) an executable test that fails now and passes after the
   change, (b) a procedural trace through the system on a representative artifact
   showing observable failure mechanics, or (c) a failure-mechanics trace with a
   concrete minimal remedy.
2. **Constraint violation** — a direct quote from CLAUDE.md, MEMORY.md, project
   rules, or a declared constraint.
3. **Efficiency regression** — a measurable complexity, token-cost or latency
   increase not offset by a gain.

Assume the person who asked will EXECUTE your evidence. If a test you cite does not
reproduce as claimed, your ballot is nullified for hallucinatory helpfulness — so
cite what you have actually reasoned through, not what would sound convincing.

## What NOT to do

- Do not restate the artifact back as analysis.
- Do not produce a list of generic best practices unattached to this code.
- Do not soften a real finding because the work looks careful.
- Do not manufacture a finding because you were asked for one.
"""

CHEAP_BODY = """
# @{name} — execution handle ({provider}, {tier})

**This is an instrument, not a persona.** You are routed work that does not need a
frontier model, so that the session spends its budget where judgement is actually
required.

{purpose}

## Scope — and why this handle carries no review protocol

This is **tier discipline, not provider diversity.** You are `provider:
{provider}`, the same provider as the frontier model driving this session, so your
agreement with it is worth very little as a cross-check — you share its blind
spots.

If the task turns out to need judgement rather than execution — an ambiguous
requirement, a design choice, a security-relevant decision — **say so and stop**
rather than guessing. Escalating costs one message; a confidently wrong mechanical
edit costs a debugging session.

For a genuine second opinion, the session should use a `review`-class handle on a
different provider instead. That is a different question from "can this be done
cheaply".

## Working rules

- Do exactly the stated task. Do not expand scope.
- If the instruction is ambiguous, ask once; do not pick an interpretation silently.
- Report what you changed, plainly, with paths.
"""


def load_roster(path: Path) -> dict:
    if yaml is None:
        raise SystemExit("render_handles: PyYAML is required (declared in the core group)")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _diversity_note(handle: dict, roster: dict) -> str:
    """Say plainly whether this handle is real diversity or same-family depth.

    Computed against the roster's DECLARED `session_provider`, never a hardcoded
    vendor. The first version assumed "anthropic", which would have silently lied
    the moment someone drove a session from a GPT model: a handle asserting
    independence it does not have is worse than no handle, because the entire
    value of a second opinion is knowing whether it is genuinely second.
    """
    provider = handle.get("provider", "unknown")
    session = roster.get("session_provider")
    if not session:
        return (" The roster does not declare `session_provider`, so whether you are"
                " independent of the model that wrote this CANNOT be determined."
                " Say so in your answer rather than implying independence.")
    if provider == session:
        return (f" The session driving you is **also {session}**, so you provide"
                " frontier-tier DEPTH, not provider diversity. Do not let your"
                " agreement be recorded as an independent confirmation — it is not.")
    return (f" The session driving you is **{session}**, so you are a genuinely"
            " different vendor: your disagreement carries real information rather"
            " than echoing the same training and the same habits back.")


def render(handle: dict, roster: dict) -> str:
    cls = handle.get("class", "review")
    body_tpl = REVIEW_BODY if cls == "review" else CHEAP_BODY
    tools = REVIEW_TOOLS if cls == "review" else CHEAP_TOOLS

    models = handle.get("model") or []
    model_block = "\n".join(f"  - {m!r}" for m in models)

    purpose = " ".join((handle.get("purpose") or "").split())

    body = body_tpl.format(
        name=handle["name"],
        provider=handle.get("provider", "unknown"),
        tier=handle.get("tier", "unknown"),
        purpose=purpose,
        diversity_note=_diversity_note(handle, roster) if cls == "review" else "",
    )

    desc = (f"{cls.capitalize()} handle on {handle.get('provider')} "
            f"({handle.get('tier')} tier). "
            + ("Independent second opinion under the two-gate deliberation protocol."
               if cls == "review" else
               "Cheap-tier execution for well-specified work."))

    return (
        "---\n"
        f"name: {handle['name']}\n"
        f"description: {desc}\n"
        f"tools: {tools}\n"
        "model:\n"
        f"{model_block}\n"
        "---\n"
        f"{GENERATED_MARKER}\n"
        f"<!-- roster: source={roster.get('source')} declared_on={roster.get('declared_on')} "
        f"os_key={roster.get('os_key')} provider={handle.get('provider')} class={cls} -->\n"
        f"{body}"
    )


def pending_handles(roster: dict) -> list:
    out = []
    for h in roster.get("handles", []):
        if any(PENDING in str(m) for m in (h.get("model") or [])):
            out.append(h["name"])
        if not h.get("model"):
            out.append(h["name"])
    return out


def _harden_streams() -> None:
    """UTF-8 with backslashreplace before anything is printed (#251, W003).

    Hardened INLINE rather than via `_meta/portable_cli.py`: this script is meant
    to run on the enterprise laptop, where the harness may not be installed, and a
    renderer that cannot start because a helper is missing is worse than one that
    repeats four lines. `backslashreplace` over `replace` for the usual reason —
    both survive, only one leaves evidence of which character broke.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")
        except (AttributeError, ValueError):
            pass


def main() -> int:
    _harden_streams()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--roster", default=str(ROSTER))
    ap.add_argument("--out", default=str(AGENTS_DIR))
    ap.add_argument("--check", action="store_true",
                    help="report what would render and what is blocked; write nothing")
    args = ap.parse_args()

    roster = load_roster(Path(args.roster))
    blocked = pending_handles(roster)

    ready = [h for h in roster.get("handles", []) if h["name"] not in blocked]
    out_dir = Path(args.out)

    for h in ready:
        dst = out_dir / f"{h['name']}.agent.md"
        if not args.check:
            dst.write_text(render(h, roster), encoding="utf-8")
        print(f"  {'would render' if args.check else 'rendered'}: {dst.name} "
              f"({h.get('provider')}, {h.get('class')})")

    if blocked:
        print()
        print(f"  BLOCKED — {len(blocked)} handle(s) have no verified model id: "
              f"{', '.join(sorted(set(blocked)))}")
        print("  A placeholder id would render a handle that appears in the picker and")
        print("  silently does not route — a wrong model id fails as a PERMISSIONS error,")
        print("  not as 'no such model'. Fill them in roster.yaml from the VS Code picker.")
        return 2

    if not ready:
        print("  nothing to render")
    return 0


if __name__ == "__main__":
    sys.exit(main())
