# Template for a generated regression-replay pytest test.
# Substituted via Python str.format with these keys:
#   {confidence_level}, {source_basis}, {source_seed}, {wiring_evidence},
#   {mode}, {seed_slug}, {scenario}, {given}, {when}, {then}, {component_id}

"""
EVO-generated test — CONFIDENCE: {confidence_level}
This test was auto-generated by Evo from {source_basis}.
It captures observed legacy behaviour, NOT a correctness specification.
Requires user review before being relied on for refactor safety.

Source seed: {source_seed}
Wiring evidence: {wiring_evidence}
Mode: {mode}
Generated by: ever-test-gen@1.0.0
"""

import pytest

EVO_MARKERS = ["evo_generated", "evo_confidence:{confidence_level}", "evo_requires_review"]


def test_{seed_slug}_regression():
    """{scenario}

    GIVEN: {given}
    WHEN:  {when}
    THEN:  {then}
    """
    pytest.skip("evo-generated stub — fill in before relying on this test")
