#!/usr/bin/env python3
"""ownership_guard.py — generated-doc banner detection + manual-edit (freshness) check.

WP-9 (adoption prerequisite — §12 C6). v1 SHIPS the banner + guard; the writer-contract
migration (amending exit-with-docs / project-documentation / forge / agent-teams to
detect the banner and refuse to hand-edit) is DEFERRED — it lands before first adoption,
NOT on the v1 build/dogfood critical path (the dogfood is shadow-only, never adopts).

Two responsibilities:
  1. is_generated(path) — detect the GENERATED banner in a doc.
  2. freshness_ok(path, expected_digest) — confirm the doc's FRESHNESS stamp matches
     the expected content digest (a manual edit changes the body but the stamp is keyed
     to `generated_from`, so a hand-edit that doesn't recompute the stamp is detectable
     ONLY if the editor also leaves the stamp — which is the point: the guard's job is to
     redirect edits to ARCHITECTURE.md, and a lint can flag a doc whose banner says
     GENERATED so reviewers know not to hand-edit it).

This module is intentionally small + dependency-light (used by lint/freshness checks).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

GENERATED_MARKER = "GENERATED by code-comprehension"
_FRESHNESS_RE = re.compile(r"FRESHNESS:v1 generated_from=([0-9a-f]{16})")


def is_generated(path: Path) -> bool:
    """True if the doc carries the code-comprehension GENERATED banner."""
    if not path.is_file():
        return False
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4096]
    except OSError:
        return False
    return GENERATED_MARKER in head


def freshness_digest(path: Path) -> Optional[str]:
    """Return the 16-hex FRESHNESS digest embedded in the doc, or None."""
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    m = _FRESHNESS_RE.search(text)
    return m.group(1) if m else None


def freshness_ok(path: Path, expected_digest: str) -> bool:
    """True iff the doc's FRESHNESS digest matches the expected content digest.

    A mismatch means the generated_from inputs changed since the doc was rendered
    (the doc is STALE and should be regenerated), or the doc was hand-edited in a way
    that desynced it. Either way the freshness/lint check fails — surfacing that this
    GENERATED doc must be regenerated, and human narrative belongs in ARCHITECTURE.md.
    """
    actual = freshness_digest(path)
    return actual is not None and actual == expected_digest


def lint_no_manual_edit(path: Path, expected_digest: str) -> int:
    """CLI lint: 0 if not a generated doc OR fresh; 2 if a generated doc is stale.

    Used by a freshness/pre-commit check to FAIL on a generated doc that no longer
    matches its inputs (the C6 "fails on manual edits" requirement: a hand-edit that
    changes the body without re-rendering leaves the stamp keyed to the OLD inputs, so
    a regenerate-and-compare detects it; absent re-render, the staleness check trips).
    """
    if not is_generated(path):
        return 0
    return 0 if freshness_ok(path, expected_digest) else 2


def main(argv: Optional[list] = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="code-comprehension.ownership-guard")
    ap.add_argument("path")
    ap.add_argument("--expected-digest", default=None,
                    help="expected 16-hex FRESHNESS digest (omit to only report)")
    ns = ap.parse_args(argv)
    p = Path(ns.path)
    gen = is_generated(p)
    dig = freshness_digest(p)
    sys.stdout.write(f"generated={gen} freshness_digest={dig}\n")
    if ns.expected_digest is not None:
        rc = lint_no_manual_edit(p, ns.expected_digest)
        if rc != 0:
            sys.stderr.write(f"STALE/EDITED: {p} digest={dig} expected={ns.expected_digest}\n")
        return rc
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
