#!/usr/bin/env python3
"""render_docs.py — deterministic, ZERO-LLM renderer for code-comprehension.

Pure function `render_all(...) → {PROJECT.md, COMPONENT.md...}`, byte-identical on
re-run GIVEN a fixed intent-map (design §5 + §11 Fix-3/Fix-4 + §12 C10/C12).

Determinism rules:
  - sorted keys / sorted iteration everywhere
  - per-run fields (sampled_at, model_id, run-id, generated_at) are STRIPPED from the
    doc body; the ONLY mutable line is the FRESHNESS stamp, which is keyed to the
    `generated_from` CONTENT hashes (not wall-clock)
  - imports intent-map-render's d1_sequence.render / d4_heatmap.render as PURE
    functions (NOT the CLI, which expects evo .ledger/ paths + HARD-RULE-5 gating)

Edge labeling (§12 C4 — HARD gate #4): every Interaction-Edges section is labeled
"structural (AST/regex)" — SCIP is DEFERRED to v2. Never imply SCIP precision.

Generated-ownership (WP-9): every generated doc carries the GENERATED banner +
`generated_from[]` so a freshness/lint check can detect manual edits.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
except ImportError:
    sys.stderr.write("FATAL: pyyaml not installed\n")
    sys.exit(1)

# Pure render functions from intent-map-render (imported, NOT shelled).
_IMR = Path.home() / ".claude" / "skills" / "intent-map-render" / "scripts"
if str(_IMR) not in sys.path:
    sys.path.insert(0, str(_IMR))
import d1_sequence  # noqa: E402
import d4_heatmap  # noqa: E402

GENERATED_BANNER = (
    "<!-- GENERATED by code-comprehension — do not hand-edit; edits are erased on "
    "regen; narrative → ARCHITECTURE.md -->"
)
EDGE_LABEL = "structural (AST/regex; SCIP deferred to v2)"
PROJECT_MD_MAX_LINES = 120
COMPONENT_MD_MAX_LINES = 160

# Fields injected per-run by intent-extract that MUST be stripped for determinism.
_PER_RUN_FIELDS = ("sampled_at", "model_id", "workspace_tree_hash", "content_hash",
                   "extractor_version", "template_hash", "consistency_score")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _strip_per_run(component: Dict[str, Any]) -> Dict[str, Any]:
    """Drop per-run/run-id fields so the rendered body is stable across cold regens."""
    return {k: v for k, v in component.items() if k not in _PER_RUN_FIELDS}


def _intent_map_for_render(intent_map: Dict[str, Any]) -> Dict[str, Any]:
    """A copy of the intent-map with per-run fields stripped from every component."""
    return {"components": [_strip_per_run(c) for c in intent_map.get("components", [])]}


def _one_line(component: Dict[str, Any]) -> str:
    intent = component.get("intent") or {}
    if isinstance(intent, dict):
        return str(intent.get("one_line", "")).strip() or "(no intent)"
    return "(no intent)"


def _confidence(component: Dict[str, Any]) -> str:
    intent = component.get("intent") or {}
    if isinstance(intent, dict):
        return str(intent.get("confidence_level", "interpretive"))
    return "interpretive"


def _component_source_paths(partition_doc: Dict[str, Any], cid: str) -> List[str]:
    for c in partition_doc.get("components", []):
        if c["id"] == cid:
            return sorted(c.get("source_paths", []))
    return []


def _component_block(partition_doc: Dict[str, Any], cid: str) -> Dict[str, Any]:
    for c in partition_doc.get("components", []):
        if c["id"] == cid:
            return c
    return {}


# ---------------------------------------------------------------------------
# External dependencies (deterministic manifest parse)
# ---------------------------------------------------------------------------


_MANIFEST_SKIP_DIRS = {".git", ".venv", "venv", "env", "node_modules", "dist",
                       "build", "site-packages", ".wiring", ".comprehension", ".tox"}


def _find_manifests(project_dir: Path, names: set, max_depth: int = 3) -> List[Path]:
    """Find manifest files by name up to max_depth, pruning vendored dirs.

    The dogfood's manifest lives at app_deploy/requirements.txt (not the repo root),
    so a bounded subdir search is required. Deterministic (sorted).
    """
    found: List[Path] = []
    base_depth = len(project_dir.parts)
    for root, dirs, files in os.walk(project_dir):
        depth = len(Path(root).parts) - base_depth
        if depth >= max_depth:
            dirs[:] = []
        dirs[:] = [d for d in dirs if d not in _MANIFEST_SKIP_DIRS and not d.startswith(".")]
        for f in files:
            if f in names:
                found.append(Path(root) / f)
    return sorted(found)


def parse_external_deps(project_dir: Path) -> List[str]:
    """Parse requirements*.txt / pyproject.toml / package.json for top-level deps.

    Searches the repo root AND bounded subdirs (manifests often live under app_deploy/
    or a service dir, not the root). Deterministic (sorted, de-duplicated). Never raises.
    """
    deps: set = set()
    # requirements*.txt
    for req in _find_manifests(project_dir, {"requirements.txt", "requirements-dev.txt"}):
        for line in req.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("-"):
                continue
            name = line.split("==")[0].split(">=")[0].split("<")[0].split("~")[0].split("[")[0].split(";")[0].strip()
            if name:
                deps.add(name)
    # package.json
    for pkg in _find_manifests(project_dir, {"package.json"}):
        try:
            data = json.loads(pkg.read_text(encoding="utf-8", errors="replace"))
            for key in ("dependencies", "devDependencies"):
                for name in (data.get(key) or {}):
                    deps.add(name)
        except (json.JSONDecodeError, OSError):
            pass
    # pyproject.toml
    import re
    for pyproject in _find_manifests(project_dir, {"pyproject.toml"}):
        txt = pyproject.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'"([A-Za-z0-9_.\-]+)\s*[=<>~]', txt):
            deps.add(m.group(1))
    return sorted(deps)


def detect_testing(project_dir: Path) -> str:
    """Auto-detect the test command/framework (reused convention). Deterministic."""
    if (project_dir / "pyproject.toml").is_file():
        txt = (project_dir / "pyproject.toml").read_text(errors="replace")
        if "pytest" in txt:
            return "pytest"
    if list(project_dir.glob("tests/test_*.py")) or list(project_dir.glob("test_*.py")):
        return "pytest (tests/ detected)"
    if (project_dir / "package.json").is_file():
        try:
            data = json.loads((project_dir / "package.json").read_text(errors="replace"))
            if "test" in (data.get("scripts") or {}):
                return f"npm test → {data['scripts']['test']}"
        except (json.JSONDecodeError, OSError):
            pass
    return "(no test infrastructure detected)"


# ---------------------------------------------------------------------------
# Edge view → component-level interaction edges
# ---------------------------------------------------------------------------


def _component_edges(edge_view: Dict[str, Any]) -> List[tuple]:
    """Distinct (src_component, dst_component) pairs, sorted. Self-edges dropped."""
    pairs: set = set()
    for e in edge_view.get("edges", []):
        src = e.get("src_component")
        dst = e.get("dst_component")
        if src and dst and src != dst:
            pairs.add((src, dst))
    return sorted(pairs)


# ---------------------------------------------------------------------------
# generated_from (content hashes — NOT wall-clock; C12 working-tree)
# ---------------------------------------------------------------------------


def build_generated_from(
    partition_doc: Dict[str, Any],
    intent_map: Dict[str, Any],
    edge_view: Dict[str, Any],
) -> Dict[str, Any]:
    """Content-hash provenance for the FRESHNESS stamp. Deterministic.

    Hashes the canonical selected source inventory (C5) + intent cache keys +
    edge-view snapshot id + records the working-tree state (C12). model_id is pinned
    (per-component) so a cold regen with a different model is detectable.
    """
    stripped = _intent_map_for_render(intent_map)
    intent_canonical = json.dumps(stripped, sort_keys=True, separators=(",", ":"))
    # model_ids pinned (read from the UN-stripped components, sorted+deduped)
    model_ids = sorted({c.get("model_id", "") for c in intent_map.get("components", []) if c.get("model_id")})
    return {
        "partition_hash": partition_doc.get("partition_hash", ""),
        "intent_map_hash": _sha256_text(intent_canonical),
        # NOT the reconciler's snapshot_id — that carries per-run wall-clock through
        # evidence[].last_seen_at (the wiring extractor's emitted_at). We hash ONLY the
        # deterministic component-edge pairs so the stamp is stable across cold runs.
        "edge_view_id": _deterministic_edge_hash(edge_view),
        "model_ids": model_ids,
        "tree_state": partition_doc.get("tree_state", {}),
        "component_count": len(partition_doc.get("components", [])),
    }


def _deterministic_edge_hash(edge_view: Dict[str, Any]) -> str:
    """Hash the sorted distinct (src_component, dst_component, edge_kind) tuples.

    Excludes all timestamps / evidence / per-run fields so two runs over the same tree
    produce the same digest (the reconciler's snapshot_id does NOT — it embeds
    emitted_at). 16-hex, deterministic."""
    triples = sorted({
        (e.get("src_component", ""), e.get("dst_component", ""), e.get("edge_kind", ""))
        for e in edge_view.get("edges", [])
    })
    canonical = json.dumps(triples, sort_keys=True, separators=(",", ":"))
    return _sha256_text(canonical)[:16]


def freshness_stamp(generated_from: Dict[str, Any]) -> str:
    """The ONLY mutable line in the doc body — keyed to content hashes (no wall-clock)."""
    canonical = json.dumps(generated_from, sort_keys=True, separators=(",", ":"))
    digest = _sha256_text(canonical)[:16]
    return f"<!-- FRESHNESS:v1 generated_from={digest} -->"


# ---------------------------------------------------------------------------
# PROJECT.md (Level 0)
# ---------------------------------------------------------------------------


def render_project_md(
    project_dir: Path,
    partition_doc: Dict[str, Any],
    intent_map: Dict[str, Any],
    edge_view: Dict[str, Any],
) -> str:
    components = sorted(intent_map.get("components", []), key=lambda c: c.get("component_id", ""))
    comp_by_id = {c.get("component_id"): c for c in components}
    component_ids = sorted(c["id"] for c in partition_doc.get("components", []))

    gen_from = build_generated_from(partition_doc, intent_map, edge_view)
    project_name = project_dir.name

    lines: List[str] = []
    # YAML header
    header = {
        "generated_by": "code-comprehension",
        "generated_from": gen_from,
        "see_also": "ARCHITECTURE.md (hand-owned narrative / why / failure-impact)",
    }
    lines.append("---")
    lines.append(yaml.safe_dump(header, sort_keys=True, default_flow_style=False).rstrip())
    lines.append("---")
    lines.append(GENERATED_BANNER)
    lines.append(freshness_stamp(gen_from))
    lines.append("")
    lines.append(f"# {project_name} — Architecture (generated)")
    lines.append("")
    lines.append("> Generated comprehension front-door. Hand-owned narrative (the *why*, "
                 "external-failure-impact, cross-repo notes) lives in **ARCHITECTURE.md**.")
    lines.append("")

    # Components table
    lines.append("## Components")
    lines.append("")
    lines.append("| Component | Source paths | One-line intent | Confidence |")
    lines.append("|---|---|---|---|")
    for cid in component_ids:
        paths = ", ".join(f"`{p}`" for p in _component_source_paths(partition_doc, cid))
        comp = comp_by_id.get(cid, {})
        lines.append(f"| `{cid}` | {paths} | {_one_line(comp)} | {_confidence(comp)} |")
    lines.append("")

    # Interaction edges (LABELED structural — HARD gate #4)
    lines.append("## Interaction Edges")
    lines.append("")
    lines.append(f"_Edges are **{EDGE_LABEL}** — derived from import/call structure, not a "
                 "symbol-precise index. Every edge below resolves to a `static.jsonl` edge._")
    lines.append("")
    edges = _component_edges(edge_view)
    if edges:
        lines.append("| From | To |")
        lines.append("|---|---|")
        for src, dst in edges:
            lines.append(f"| `{src}` | `{dst}` |")
    else:
        lines.append("_No cross-component structural edges detected._")
    lines.append("")

    # External dependencies
    deps = parse_external_deps(project_dir)
    lines.append("## External Dependencies")
    lines.append("")
    if deps:
        lines.append(", ".join(f"`{d}`" for d in deps))
    else:
        lines.append("_None detected from manifests._")
    lines.append("")

    # Entry points
    lines.append("## Entry Points")
    lines.append("")
    ep_lines: List[str] = []
    for cid in component_ids:
        comp = comp_by_id.get(cid, {})
        for ep in sorted((comp.get("entry_points") or []),
                         key=lambda e: json.dumps(e, sort_keys=True) if isinstance(e, dict) else str(e)):
            if isinstance(ep, dict):
                ep_lines.append(f"- `{cid}`: {ep.get('kind', '?')} {ep.get('detail', '')}".rstrip())
        # partition-level entry-point markers (structural)
        block = _component_block(partition_doc, cid)
        for marker in sorted(block.get("entry_points", [])):
            ep_lines.append(f"- `{cid}`: structural entry-point `{marker}`")
    if ep_lines:
        # dedupe preserving sorted order
        seen = set()
        for ln in ep_lines:
            if ln not in seen:
                lines.append(ln)
                seen.add(ln)
    else:
        lines.append("_No entry points detected._")
    lines.append("")

    # Testing
    lines.append("## Testing")
    lines.append("")
    lines.append(detect_testing(project_dir))
    lines.append("")

    body = "\n".join(lines).rstrip() + "\n"
    return body


# ---------------------------------------------------------------------------
# COMPONENT.md (Level 1)
# ---------------------------------------------------------------------------


def render_component_md(
    project_dir: Path,
    partition_doc: Dict[str, Any],
    component: Dict[str, Any],
    edge_view: Dict[str, Any],
    generated_from: Dict[str, Any],
) -> str:
    cid = component.get("component_id", "unknown")
    block = _component_block(partition_doc, cid)
    single_map = {"components": [_strip_per_run(component)]}

    lines: List[str] = []
    lines.append("---")
    lines.append(yaml.safe_dump({"generated_by": "code-comprehension", "component": cid},
                                sort_keys=True).rstrip())
    lines.append("---")
    lines.append(GENERATED_BANNER)
    lines.append(freshness_stamp(generated_from))
    lines.append("")
    lines.append(f"# {cid} (component)")
    lines.append("")

    # Purpose
    lines.append("## Purpose")
    lines.append("")
    lines.append(_one_line(component))
    intent = component.get("intent") or {}
    if isinstance(intent, dict):
        for r in (intent.get("responsibilities") or []):
            lines.append(f"- {r}")
    lines.append("")
    lines.append(f"_Confidence: **{_confidence(component)}** | intent_mode: "
                 f"**{block.get('intent_mode', 'unknown')}**_")
    lines.append("")

    # Interfaces (structural)
    lines.append("## Interfaces (structural)")
    lines.append("")
    eps = sorted((component.get("entry_points") or []),
                 key=lambda e: json.dumps(e, sort_keys=True) if isinstance(e, dict) else str(e))
    if eps:
        for ep in eps:
            if isinstance(ep, dict):
                lines.append(f"- {ep.get('kind', '?')} — `{ep.get('handler_symbol', ep.get('detail', '?'))}`")
    else:
        lines.append("_No public interface symbols extracted._")
    lines.append("")

    # Internal flow — D1 via the PURE render fn
    lines.append("## Internal Flow")
    lines.append("")
    d1 = d1_sequence.render_single_component(_strip_per_run(component))
    lines.append(d1)
    lines.append("")

    # Key files
    lines.append("## Key Files")
    lines.append("")
    files = sorted(block.get("source_files", []))[:20]
    for f in files:
        lines.append(f"- `{f}`")
    if len(block.get("source_files", [])) > 20:
        lines.append(f"- _… {len(block['source_files']) - 20} more_")
    lines.append("")

    # Edge cases (error paths)
    lines.append("## Edge Cases")
    lines.append("")
    errs = sorted((component.get("error_paths") or []),
                  key=lambda e: json.dumps(e, sort_keys=True) if isinstance(e, dict) else str(e))
    if errs:
        for er in errs:
            if isinstance(er, dict):
                lines.append(f"- {er.get('error_kind', 'raises')} on {er.get('condition', '?')}")
    else:
        lines.append("_No error paths extracted._")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Top-level
# ---------------------------------------------------------------------------


def render_all(
    *,
    project_dir: Path,
    out_dir: Path,
    partition_doc: Dict[str, Any],
    intent_map: Dict[str, Any],
    edge_view: Dict[str, Any],
    shadow: bool = True,
) -> Dict[str, Any]:
    """Render the shadow PROJECT.md + per-component COMPONENT.md. Deterministic.

    shadow=True (default) writes to .comprehension/PROJECT.generated.md and
    .comprehension/components/<id>/COMPONENT.md — NEVER the repo's real docs.
    Returns {project_md, component_dir, components: [...]}.
    """
    project_dir = project_dir.resolve()
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    project_body = render_project_md(project_dir, partition_doc, intent_map, edge_view)
    gen_from = build_generated_from(partition_doc, intent_map, edge_view)

    if shadow:
        project_md_path = out_dir / "PROJECT.generated.md"
        comp_root = out_dir / "components"
    else:
        project_md_path = project_dir / "PROJECT.md"
        comp_root = project_dir / "docs" / "components"

    _atomic_write(project_md_path, project_body)

    comp_root.mkdir(parents=True, exist_ok=True)
    rendered_components: List[str] = []
    for component in sorted(intent_map.get("components", []), key=lambda c: c.get("component_id", "")):
        cid = component.get("component_id", "unknown")
        cdir = comp_root / cid
        cdir.mkdir(parents=True, exist_ok=True)
        body = render_component_md(project_dir, partition_doc, component, edge_view, gen_from)
        _atomic_write(cdir / "COMPONENT.md", body)
        rendered_components.append(cid)

    return {
        "project_md": str(project_md_path),
        "component_dir": str(comp_root),
        "components": rendered_components,
        "generated_from": gen_from,
        "shadow": shadow,
    }


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    os.replace(str(tmp), str(path))


# ---------------------------------------------------------------------------
# CLI (for standalone render from a partition + intent-map on disk)
# ---------------------------------------------------------------------------


def main(argv: Optional[List[str]] = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="code-comprehension.render")
    ap.add_argument("--project-dir", required=True)
    ap.add_argument("--partition-doc", required=True, help="synthetic-contract-map.yaml")
    ap.add_argument("--intent-map", required=True, help="merged {components:[...]} yaml/json")
    ap.add_argument("--edge-view", default=None, help="reconciler snapshot json (optional)")
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--no-shadow", action="store_true")
    ns = ap.parse_args(argv)

    project_dir = Path(ns.project_dir)
    partition_doc = yaml.safe_load(Path(ns.partition_doc).read_text())
    raw = Path(ns.intent_map).read_text()
    try:
        intent_map = json.loads(raw)
    except json.JSONDecodeError:
        intent_map = yaml.safe_load(raw)
    if "components" not in intent_map:
        intent_map = {"components": intent_map if isinstance(intent_map, list) else []}
    edge_view = {}
    if ns.edge_view and Path(ns.edge_view).is_file():
        edge_view = json.loads(Path(ns.edge_view).read_text())
    out_dir = Path(ns.out_dir) if ns.out_dir else (project_dir / ".comprehension")
    result = render_all(project_dir=project_dir, out_dir=out_dir,
                        partition_doc=partition_doc, intent_map=intent_map,
                        edge_view=edge_view, shadow=not ns.no_shadow)
    sys.stdout.write(json.dumps(result, sort_keys=True, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
